---
title: "Final_Project_Work"
author: "Bobby Current"
date: "11/25/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rstanarm)
library(readxl)
library(janitor)
library(gt)
library(gtsummary)
library(broom.mixed)
```


```{r relevent data}
#Only the stuff I used ended up over here.

presidential_elections <- read_csv("Raw_Data/countypres_2000-2016.csv") %>%
  mutate(vote_prop = (candidatevotes / totalvotes)) %>%
  mutate(percent_won = (vote_prop * 100)) %>%
  filter(party %in% c("democrat", "republican")) %>%
  pivot_wider(id_cols = c(FIPS, year, state),
              names_from = party,
              values_from = c(percent_won, candidate))



students_2012 <- read_csv("Raw_Data/non_fiscal_2012.csv", col_types = cols(MEMBER = col_double(),
                                                                           LEAID = col_double())) %>%
  clean_names() %>%
  select(member, leaid) 

spending_2012 <- read_csv("Raw_Data/district_spending_2011.csv", 
                          col_types = cols(name = col_character(),
                                           stname = col_character(),
                                           stabbr = col_character())) %>%
  clean_names() %>%
  left_join(students_2012, by = "leaid") %>%
  select(conum, 
         name, 
         stname, 
         stabbr, 
         totalrev,
         totalexp, 
         tlocrev, 
         tstrev, 
         tfedrev,
         leaid,
         total_students = member) %>%
  mutate(year = 2012) %>%
  mutate(percent_local = ((tlocrev / totalrev) * 100)) %>%
  mutate(percent_federal = ((tfedrev / totalrev) * 100)) %>%
  mutate(percent_state = ((tstrev / totalrev) * 100)) %>%
  filter(!is.na(total_students)) %>%
  mutate(per_capita_rev = (totalrev / total_students)) %>%
  filter(total_students > 0) %>%
  mutate(per_capita_exp = (totalrev / total_students))



students_2008 <- read_csv("Raw_Data/non_fiscal_2008.csv", col_types = cols(PK1207 = col_double(),
                                                                          LEAID = col_double())) %>%
  clean_names() %>%
  select(pk1207, leaid)

spending_2008 <- read_csv("Raw_Data/district_spending_2008.csv",
                          col_types = cols(name = col_character(), 
                                           stname = col_character(), 
                                           stabbr = col_character())) %>%
  clean_names() %>%
  left_join(students_2008, by = "leaid") %>%
  select(conum, 
         name, 
         stname, 
         stabbr, 
         totalrev, 
         totalexp, 
         tlocrev,
         tstrev, 
         tfedrev,
         leaid,
         total_students = pk1207) %>%
  mutate(year = 2008) %>%
  mutate(percent_local = ((tlocrev / totalrev) * 100)) %>%
  mutate(percent_federal = ((tfedrev / totalrev) * 100)) %>%
  mutate(percent_state = ((tstrev / totalrev) * 100)) %>%
  filter(!is.na(total_students)) %>%
  mutate(per_capita_rev = (totalrev / total_students)) %>%
  filter(total_students > 0) %>%
  mutate(per_capita_exp = (totalrev / total_students))




spending_2004 <- read_csv("Raw_Data/district_spending_2004.csv",
                          col_types = cols(name = col_character(),
                                           stname = col_character(),
                                           stabbr = col_character())) %>%
  clean_names() %>%
  select(conum, 
         name, 
         stname, 
         stabbr, 
         totalrev, 
         totalexp, 
         tlocrev, 
         tstrev, 
         tfedrev,
         leaid) %>%
  mutate(year = 2004) %>%
  mutate(percent_local = ((tlocrev / totalrev) * 100)) %>%
  mutate(percent_federal = ((tfedrev / totalrev) * 100)) %>%
  mutate(percent_state = ((tstrev / totalrev) * 100))
  


students_2016 <- read_csv("Raw_Data/membership_2016.csv",
                          col_types = cols(TOTAL = col_double(),
                                           LEAID = col_double())) %>%
  clean_names() %>%
  select(total, leaid)

spending_2016 <- read_csv("Raw_Data/district_spending_2016.csv", 
                          col_types = cols(name = col_character(),
                                           stname = col_character(),
                                           stabbr = col_character())) %>%
  clean_names() %>%
  left_join(students_2016, by = "leaid") %>%
  select(conum,
         name,
         stname,
         stabbr,
         totalrev,
         totalexp,
         tlocrev,
         tfedrev,
         tstrev,
         leaid,
         total_students = total) %>%
  mutate(year = 2016) %>%
  mutate(percent_local = ((tlocrev / totalrev) * 100)) %>%
  mutate(percent_federal = ((tfedrev / totalrev) * 100)) %>%
  mutate(percent_state = ((tstrev / totalrev) * 100)) %>%
  filter(!is.na(total_students)) %>%
  mutate(per_capita_rev = totalrev / total_students) %>%
  filter(total_students > 0) %>%
  mutate(per_capita_exp = (totalrev / total_students))



joined_temp <- bind_rows(spending_2004, spending_2008, spending_2012, spending_2016)



spending_2000 <- read_csv("Raw_Data/district_spending_2000.csv",
                          col_types = cols(name = col_character(),
                                           stname = col_character(),
                                           stabbr = col_character())) %>%
  clean_names() %>%
  select(name, 
         stname, 
         stabbr, 
         totalrev, 
         totalexp, 
         tlocrev, 
         tstrev, 
         tfedrev,
         leaid) %>%
  left_join(joined_temp, by = "name") %>%
  filter(!is.na(conum)) %>%
  distinct(conum, .keep_all = TRUE) %>%
  select(name, 
         stname = stname.x, 
         stabbr = stabbr.x, 
         totalrev = totalrev.x, 
         totalexp = totalexp.x, 
         tlocrev = tlocrev.x, 
         tstrev = tstrev.x, 
         tfedrev = tfedrev.x,
         conum,
         leaid = leaid.x) %>%
  mutate(year = 2000) %>%
  mutate(percent_local = ((tlocrev / totalrev) * 100)) %>%
  mutate(percent_federal = ((tfedrev / totalrev) * 100)) %>%
  mutate(percent_state = ((tstrev / totalrev) * 100))
  


final_data <- bind_rows(joined_temp, spending_2000) %>%
  left_join(presidential_elections, by = c("conum" = "FIPS", "year"))


```





```{r carPlot}

final_data %>%
  #filter(year == 2016) %>%
  #filter(stabbr == "SC") %>%
  ggplot(aes(x = totalexp, y = percent_won_democrat)) +
  
#I think I am going to add an alpha argument to this.
  
  geom_point(alpha = 0.25) +
  geom_smooth(method = "lm") +
  scale_x_log10() +
  facet_wrap(~ year) +
  labs(title = "School Spending and Democratic Vote Share in Presidential Elections", 
       subtitle = "Democratic vote share in United States since the 2000 election", 
       x = "Education Spending Per District", 
       y = "Percent of vote for Democratic Candidate") +
  theme_bw()



```

```{r yearPlot}
#This chunk messed me up when I tried to run everything, 
#since it is ready for shiny already.
#input$years and input$state is one hundred percent shiny.

final_data %>%
  filter(input$years) %>%
  filter(stabbr == input$state) %>%
  ggplot(aes(x = totalexp, y = percent_won_democrat)) +
  geom_point() +
  geom_smooth(method = "lm") +
  scale_x_log10() +
  facet_wrap(~ year) +
  labs(title = "School Spending and Democratic Vote Share in Presidential Elections", 
       subtitle = "2000 to 2016 Presidential Elections", 
       x = "Education Spending Per District", 
       y = "Percent of vote for Democratic Candidate") +
  theme_bw()





```



```{r yearPlot examples}
#I don't know if I want to add an alpha argument to shiny.

final_data %>%
  #filter(year == 2016) %>%
  filter(stabbr == "OH") %>%
  ggplot(aes(x = totalexp, y = percent_won_democrat)) +
  geom_point(alpha = 0.4) +
  geom_smooth(method = "lm") +
  scale_x_log10() +
  facet_wrap(~ year) +
  labs(title = "School Spending and Democratic Vote Share in Presidential Elections", 
       subtitle = "Democratic vote share in United States since the 2000 election", 
       x = "Education Spending Per District", 
       y = "Percent of vote for Democratic Candidate") +
  theme_bw()





```




```{r stan}
#Stan is useless for stuff by each dollar, so I made this so that I could see 
#the affect per million or thousand dollars.
#I should mention this in my shiny app somewhere.

final_data_million <- 
  final_data %>%
  filter(year %in% c(2008, 2012, 2016)) %>%
  mutate(Total_Expenditure = (totalexp / 1000000)) %>%
  mutate(Total_Revenue = (totalrev / 1000000)) %>%
  mutate(Total_State_Revenue = (tstrev / 1000000)) %>%
  mutate(stname = toupper(stname)) %>%
  mutate(Per_Capita_Revenue = (per_capita_rev / 1000)) %>%
  mutate(Per_Capita_Expenditure = (per_capita_exp / 1000)) %>%
  mutate(Total_Students = total_students)

data_stan <- stan_glm(data = final_data_million,
                      formula = percent_won_democrat ~ total_students + per_capita_rev_mil + total_students:per_capita_rev_mil,
                      refresh = 0)

print(data_stan, digits = 9)



other_stan <- stan_glm(data = final_data_million,
         formula = percent_won_democrat ~ per_capita_exp_mil:per_capita_rev_mil + total_students,
         refresh = 0)

print(other_stan, digits = 9)



total_stan <- stan_glm(data = final_data_million,
                       formula = percent_won_democrat ~ totalrev + totalexp,
                       refresh = 0)

print(total_stan, digits = 9)



```


```{r tables}

other_stan <- stan_glm(data = final_data_million,
         formula = percent_won_democrat ~ Per_Capita_Expenditure:Per_Capita_Revenue 
         + Total_Students,
         refresh = 0)


other_stan %>%
  tbl_regression(intercept = TRUE,
                 exponentiate = TRUE,
                 estimate_fun = function(other_stan)
                 style_sigfig(other_stan, digits = 9)) %>%
  as_gt() %>%
  tab_header(subtitle = "Effect of Total Students and School Spending on 
             Democratic Vote Share",
             title = "Regression of Democratic Vote Share in Presidential 
             Elections")

```

```{r other table}
total_stan <- stan_glm(data = final_data_million,
                       formula = percent_won_democrat ~ Total_Revenue + Total_Expenditure,
                       refresh = 0)

total_stan %>%
  tbl_regression(intercept = TRUE,
                 exponentiate = TRUE,
                 estimate_fun = function(total_stan)
                 style_sigfig(total_stan, digits = 9)) %>%
  as_gt() %>%
  tab_header(subtitle = "Effect of School Spending on 
             Democratic Vote Share",
             title = "Regression of Democratic Vote Share in Presidential 
             Elections")




```


```{r}
final_data %>%
  filter(year %in% c(2008, 2012, 2016)) %>%
  filter(stabbr == "TX") %>%
  ggplot(aes(x = per_capita_exp, y = percent_won_democrat)) +
  geom_point() +
  geom_smooth(method = "lm") +
  scale_x_log10() +
  facet_wrap(~ year) +
  labs(title = "School Spending and Democratic Vote Share in Presidential Elections", 
       subtitle = "Democratic vote share in United States since the 2008 election", 
       x = "Education Spending Per Student Per District", 
       y = "Percent of vote for Democratic Candidate") +
  theme_bw()





```

```{r}
saveRDS(final_data, file = "saved_file")

readRDS("saved_file")


saveRDS(final_data_million, file = "stan_data")

readRDS("stan_data")



```


