---
title: "Data_Stuff"
author: "Bobby Current"
date: "10/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(janitor)
library(rstanarm)
```

```{r}
school_spending_2017_2018 <-
spending_data_2018 <-
  read_excel("Raw_Data/Stfis180_1a.xlsx") %>%
group_by(STNAME) %>%
  select(STNAME, E11A)
  

districts_by_county <- read_excel("Raw_Data/grf19_lea_county.xlsx") %>%
  mutate(NAME_LEA19_UPPER = toupper(NAME_LEA19))

districts_by_county


spending_2012 <- read_csv("Raw_Data/district_spending_2011.csv")

plot_1 <- school_spending_2017_2018 %>%
  ggplot(aes(x = STNAME, y = E11A)) +
  geom_col() +
  labs(x = "State", 
       y = "Total Amount Paid", 
       title = "The Total Amount Paid to Teachers in 
       Regular Education Programs by State", 
       subtitle = "2017 - 2018 School Year") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))


district_spending <- read_csv("Raw_Data/archive/districts.csv") 


presidential_elections <- read_csv("Raw_Data/countypres_2000-2016.csv") %>%
  mutate(vote_prop = (candidatevotes / totalvotes)) %>%
  mutate(percent_won = (vote_prop * 100)) %>%
  filter(party %in% c("democrat", "republican")) %>%
  pivot_wider(id_cols = c(FIPS, year, state),
              names_from = party,
              values_from = c(percent_won, candidate))
  
  presidential_elections

spending_by_state <- read_excel("Raw_Data/tabn236.25.xls", skip = 2) %>%
  clean_names()

spending_per_student_by_state <- read_excel("Raw_Data/public-school-per-pupil-expenditures.xlsx", skip = 3) %>%
  clean_names()

  
```



```{r join}

districts_and_counties <- left_join(district_spending, districts_by_county, by = c("NAME" = "NAME_LEA19_UPPER")) %>%
  mutate(NAME_COUNTY19 = str_replace(NAME_COUNTY19, "County", ""))


left_join(districts_and_counties, presidential_elections, by = c("NAME_COUNTY19" = "county"))








```

```{r district spending}

#Select relevant columns, mutate year column for each one. Join all of them together, by year and district, full join. Only add president stuff after this step.

spending_2012 <- read_csv("Raw_Data/district_spending_2011.csv", 
                          col_types = cols(name = col_character(),
                                           stname = col_character(),
                                           stabbr = col_character())) %>%
  clean_names() %>%
  select(conum, 
         name, 
         stname, 
         stabbr, 
         totalrev,
         totalexp, 
         tlocrev, 
         tstrev, 
         tfedrev) %>%
  mutate(year = 2012) %>%
  mutate(percent_local = ((tlocrev / totalrev) * 100)) %>%
  mutate(percent_federal = ((tfedrev / totalrev) * 100)) %>%
  mutate(percent_state = ((tstrev / totalrev) * 100))




spending_2008 <- read_csv("Raw_Data/district_spending_2008.csv",
                          col_types = cols(name = col_character(), 
                                           stname = col_character(), 
                                           stabbr = col_character())) %>%
  clean_names() %>%
  select(conum, 
         name, 
         stname, 
         stabbr, 
         totalrev, 
         totalexp, 
         tlocrev,
         tstrev, 
         tfedrev) %>%
  mutate(year = 2008) %>%
  mutate(percent_local = ((tlocrev / totalrev) * 100)) %>%
  mutate(percent_federal = ((tfedrev / totalrev) * 100)) %>%
  mutate(percent_state = ((tstrev / totalrev) * 100))



spending_2004 <- read_csv("Raw_Data/district_spending_2004.csv",
                          col_types = cols(name = col_character(),
                                           stname = col_character(),
                                           stabbr = col_character())) %>%
  clean_names() %>%
  select(conum, 
         name, 
         stname, 
         stabbr, 
         totalrev, 
         totalexp, 
         tlocrev, 
         tstrev, 
         tfedrev) %>%
  mutate(year = 2004) %>%
  mutate(percent_local = ((tlocrev / totalrev) * 100)) %>%
  mutate(percent_federal = ((tfedrev / totalrev) * 100)) %>%
  mutate(percent_state = ((tstrev / totalrev) * 100))
  


spending_2016 <- read_csv("Raw_Data/district_spending_2016.csv", 
                          col_types = cols(name = col_character(),
                                           stname = col_character(),
                                           stabbr = col_character())) %>%
  clean_names() %>%
  select(conum,
         name,
         stname,
         stabbr,
         totalrev,
         totalexp,
         tlocrev,
         tfedrev,
         tstrev) %>%
  mutate(year = 2016) %>%
  mutate(percent_local = ((tlocrev / totalrev) * 100)) %>%
  mutate(percent_federal = ((tfedrev / totalrev) * 100)) %>%
  mutate(percent_state = ((tstrev / totalrev) * 100))



joined_temp <- bind_rows(spending_2004, spending_2008, spending_2012, spending_2016)



spending_2000 <- read_csv("Raw_Data/district_spending_2000.csv",
                          col_types = cols(name = col_character(),
                                           stname = col_character(),
                                           stabbr = col_character())) %>%
  clean_names() %>%
  select(name, 
         stname, 
         stabbr, 
         totalrev, 
         totalexp, 
         tlocrev, 
         tstrev, 
         tfedrev) %>%
  left_join(joined_temp, by = "name") %>%
  filter(!is.na(conum)) %>%
  distinct(conum, .keep_all = TRUE) %>%
  select(name, 
         stname = stname.x, 
         stabbr = stabbr.x, 
         totalrev = totalrev.x, 
         totalexp = totalexp.x, 
         tlocrev = tlocrev.x, 
         tstrev = tstrev.x, 
         tfedrev = tfedrev.x,
         conum) %>%
  mutate(year = 2000) %>%
  mutate(percent_local = ((tlocrev / totalrev) * 100)) %>%
  mutate(percent_federal = ((tfedrev / totalrev) * 100)) %>%
  mutate(percent_state = ((tstrev / totalrev) * 100))
  


```

```{r new joins}


final_data <- bind_rows(joined_temp, spending_2000) %>%
  left_join(presidential_elections, by = c("conum" = "FIPS", "year"))


```

```{r plots}

final_data %>%
  #filter(year == 2016) %>%
  filter(stabbr == "TN") %>%
  ggplot(aes(x = totalexp, y = percent_won_democrat)) +
  geom_point() +
  geom_smooth(method = "lm") +
  scale_x_log10() +
  facet_wrap(~ year) +
  labs(title = "School Spending and Democratic Vote Share in Presidential Elections", subtitle = "Democratic vote share in US States since the 2000 election", x = "Presidential Elections From 2000 to 2016", y = "Percent of vote for Democratic Candidate")





```


```{r}

```




```{r non fiscal stuff}
students_2008 <- read_csv("Raw_Data/non_fiscal_2008.csv") %>%
  clean_names() %>%
  select(conum07, pk1207, name07) %>%
  mutate(year = 2008)



students_2012 <- read_csv("Raw_Data/non_fiscal_2012.csv") %>%
  clean_names() %>%
  select(conum, name, member) %>%
  mutate(year = 2012)



# left_join(spending_2008, students_2008, by = "conum")

```


```{r}

county_codes <- read_csv("Raw_Data/county_codes.csv") %>%
  clean_names() %>%
  select(1:2) %>%
  mutate(conum = gsub("^.", "", stcou)) %>%
  mutate(conum = as.double(conum))


district_finances_16_17 <- read_csv("Raw_Data/district_finances_16_17.csv") %>%
  clean_names()

district_codes_2016_17 <- left_join(district_finances_16_17, county_codes, by = "conum") %>%
  group_by(conum) %>%
  
  # Join before summarizing
  
 # summarize(tfedrev = sum(tfedrev), totalrev = sum(totalrev), totalexp = sum(totalexp), area_name) %>%
  separate(area_name, 
           into = c("county", "state"), 
           sep = ", ") %>%
  left_join(presidential_elections, by = c("county", "state" = "state_po"))

```

